/**
 * Athena V2 - Payroll Excel Export
 *
 * Generates a styled .xlsx workbook for a finalized PayrollRun.
 * Sheets:
 *   1. Summary    — totals at a glance
 *   2. Payroll Register — one row per employee, all components as columns
 *   3. Reimbursement Detail — one row per approved claim included in this run
 */

import ExcelJS from 'exceljs';

export interface ExportEntry {
  employeeId:     string;
  name:           string;
  department:     string;
  designation:    string;
  monthlyCtc:     number;
  workingDays:    number;
  lwpDays:        number;
  paidDays:       number;
  earnings:       Record<string, number>;
  deductions:     Record<string, number>;
  reimbursements: number;
  grossPay:       number;
  totalDeductions:number;
  netPay:         number;
}

export interface ReimbursementDetail {
  employeeId:   string;
  employeeName: string;
  category:     string;
  amount:       number;
  description:  string;
  submittedOn:  string;
}

export interface ExportOptions {
  month:            number;
  year:             number;
  earningColumns:   string[];   // ordered earning component names
  deductionColumns: string[];   // ordered deduction component names (excl. LWP Deduction)
  entries:          ExportEntry[];
  reimbDetails:     ReimbursementDetail[];
}

// Brand colours
const PURPLE = 'FF361963';
const ORANGE = 'FFFD8C27';
const WHITE  = 'FFFFFFFF';
const LIGHT_GREY = 'FFF5F5F5';
const BORDER_GREY = 'FFD0D0D0';

function headerStyle(bg = PURPLE): Partial<ExcelJS.Style> {
  return {
    font:      { bold: true, color: { argb: WHITE }, size: 11 },
    fill:      { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } },
    alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
    border: {
      top:    { style: 'thin', color: { argb: BORDER_GREY } },
      bottom: { style: 'thin', color: { argb: BORDER_GREY } },
      left:   { style: 'thin', color: { argb: BORDER_GREY } },
      right:  { style: 'thin', color: { argb: BORDER_GREY } },
    },
  };
}

function dataStyle(shade = false): Partial<ExcelJS.Style> {
  return {
    font:      { size: 10 },
    fill:      shade ? { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT_GREY } } : { type: 'pattern', pattern: 'none' },
    alignment: { horizontal: 'center', vertical: 'middle' },
    border: {
      top:    { style: 'hair', color: { argb: BORDER_GREY } },
      bottom: { style: 'hair', color: { argb: BORDER_GREY } },
      left:   { style: 'hair', color: { argb: BORDER_GREY } },
      right:  { style: 'hair', color: { argb: BORDER_GREY } },
    },
  };
}

function currency(n: number): string {
  return `₹${n.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

const MONTH_NAMES = [
  '', 'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

export async function generatePayrollExcel(opts: ExportOptions): Promise<ExcelJS.Buffer> {
  const { month, year, earningColumns, deductionColumns, entries, reimbDetails } = opts;
  const monthName = MONTH_NAMES[month];
  const title     = `Payroll — ${monthName} ${year}`;

  const workbook = new ExcelJS.Workbook();
  workbook.creator  = 'Athena HRMS';
  workbook.created  = new Date();
  workbook.modified = new Date();

  // ── Sheet 1: Summary ───────────────────────────────────────────────────────
  const summarySheet = workbook.addWorksheet('Summary', {
    pageSetup: { orientation: 'portrait', fitToPage: true },
  });

  summarySheet.mergeCells('A1:C1');
  const titleCell = summarySheet.getCell('A1');
  titleCell.value = title;
  titleCell.style = {
    font:      { bold: true, size: 16, color: { argb: WHITE } },
    fill:      { type: 'pattern', pattern: 'solid', fgColor: { argb: PURPLE } },
    alignment: { horizontal: 'center', vertical: 'middle' },
  };
  summarySheet.getRow(1).height = 36;

  summarySheet.mergeCells('A2:C2');
  const subtitleCell = summarySheet.getCell('A2');
  subtitleCell.value = `Generated by Athena HRMS — Ewards`;
  subtitleCell.style = {
    font:      { italic: true, size: 10, color: { argb: 'FF888888' } },
    alignment: { horizontal: 'center', vertical: 'middle' },
  };
  summarySheet.getRow(2).height = 20;

  summarySheet.addRow([]);

  const totalEmployees     = entries.length;
  const totalGross         = entries.reduce((s, e) => s + e.grossPay, 0);
  const totalDeductions    = entries.reduce((s, e) => s + e.totalDeductions, 0);
  const totalReimbursements = entries.reduce((s, e) => s + e.reimbursements, 0);
  const totalNet           = entries.reduce((s, e) => s + e.netPay, 0);
  const totalLwpDeductions = entries.reduce((s, e) => s + (e.deductions['LWP Deduction'] ?? 0), 0);
  const totalPT            = entries.reduce((s, e) => s + (e.deductions['Professional Tax'] ?? 0), 0);

  const summaryData = [
    ['Metric',                'Value'],
    ['Period',                `${monthName} ${year}`],
    ['Total Employees',       totalEmployees],
    ['Total Gross Pay',       currency(totalGross)],
    ['Total LWP Deductions',  currency(totalLwpDeductions)],
    ['Total Professional Tax',currency(totalPT)],
    ['Total Deductions',      currency(totalDeductions)],
    ['Total Reimbursements',  currency(totalReimbursements)],
    ['Total Net Pay',         currency(totalNet)],
  ];

  summaryData.forEach((row, i) => {
    const r = summarySheet.addRow(row);
    r.getCell(1).style = headerStyle(i === 0 ? PURPLE : ORANGE);
    r.getCell(2).style = {
      font:      { bold: i === 0, size: 11, color: { argb: i === 0 ? WHITE : 'FF333333' } },
      fill:      { type: 'pattern', pattern: 'solid', fgColor: { argb: i === 0 ? PURPLE : LIGHT_GREY } },
      alignment: { horizontal: i === 0 ? 'center' : 'left', vertical: 'middle' },
      border: {
        top:    { style: 'thin', color: { argb: BORDER_GREY } },
        bottom: { style: 'thin', color: { argb: BORDER_GREY } },
        left:   { style: 'thin', color: { argb: BORDER_GREY } },
        right:  { style: 'thin', color: { argb: BORDER_GREY } },
      },
    };
    r.height = 22;
  });

  summarySheet.getColumn(1).width = 28;
  summarySheet.getColumn(2).width = 22;

  // ── Sheet 2: Payroll Register ──────────────────────────────────────────────
  const regSheet = workbook.addWorksheet('Payroll Register', {
    pageSetup: { orientation: 'landscape', fitToPage: true },
  });

  // All deduction cols including LWP Deduction (always first if present)
  const lwpExists = entries.some((e) => (e.deductions['LWP Deduction'] ?? 0) > 0);
  const allDeductionCols: string[] = [
    ...(lwpExists ? ['LWP Deduction'] : []),
    ...deductionColumns,
  ];

  // Header row
  const headerRow = [
    'Emp ID', 'Name', 'Department', 'Designation',
    'Annual CTC (₹)', 'Monthly CTC (₹)', 'Working Days', 'LWP Days', 'Paid Days',
    ...earningColumns.map((c) => `${c} (₹)`),
    'Gross Pay (₹)',
    ...allDeductionCols.map((c) => `${c} (₹)`),
    'Total Deductions (₹)',
    'Reimbursements (₹)',
    'Net Pay (₹)',
  ];

  const hRow = regSheet.addRow(headerRow);
  hRow.height = 40;
  hRow.eachCell((cell) => {
    cell.style = headerStyle();
  });

  // Data rows
  entries.forEach((entry, idx) => {
    const shade = idx % 2 === 1;
    const rowData = [
      entry.employeeId,
      entry.name,
      entry.department,
      entry.designation,
      entry.monthlyCtc * 12,
      entry.monthlyCtc,
      entry.workingDays,
      entry.lwpDays,
      entry.paidDays,
      ...earningColumns.map((c) => entry.earnings[c] ?? 0),
      entry.grossPay,
      ...allDeductionCols.map((c) => entry.deductions[c] ?? 0),
      entry.totalDeductions,
      entry.reimbursements,
      entry.netPay,
    ];

    const r = regSheet.addRow(rowData);
    r.height = 20;
    r.eachCell((cell, colIdx) => {
      const isNetPay = colIdx === rowData.length;
      cell.style = {
        ...dataStyle(shade),
        font: {
          size: 10,
          bold: isNetPay,
          color: isNetPay ? { argb: PURPLE } : { argb: 'FF333333' },
        },
        numFmt: colIdx > 4 && typeof cell.value === 'number' ? '#,##0.00' : undefined,
        alignment: { horizontal: colIdx <= 4 ? 'left' : 'center', vertical: 'middle' },
      };
    });
  });

  // Totals row
  const totalsData = [
    'TOTAL', '', '', '', '',
    currency(entries.reduce((s, e) => s + e.monthlyCtc, 0)),
    '', '', '',
    ...earningColumns.map((c) => currency(entries.reduce((s, e) => s + (e.earnings[c] ?? 0), 0))),
    currency(totalGross),
    ...allDeductionCols.map((c) => currency(entries.reduce((s, e) => s + (e.deductions[c] ?? 0), 0))),
    currency(totalDeductions),
    currency(totalReimbursements),
    currency(totalNet),
  ];
  const tRow = regSheet.addRow(totalsData);
  tRow.height = 24;
  tRow.eachCell((cell) => {
    cell.style = {
      font:      { bold: true, size: 10, color: { argb: WHITE } },
      fill:      { type: 'pattern', pattern: 'solid', fgColor: { argb: ORANGE } },
      alignment: { horizontal: 'center', vertical: 'middle' },
      border: {
        top:    { style: 'medium', color: { argb: BORDER_GREY } },
        bottom: { style: 'medium', color: { argb: BORDER_GREY } },
        left:   { style: 'thin',   color: { argb: BORDER_GREY } },
        right:  { style: 'thin',   color: { argb: BORDER_GREY } },
      },
    };
  });

  // Auto-width columns
  regSheet.columns.forEach((col, i) => {
    const header = headerRow[i] ?? '';
    const maxLen = Math.max(
      header.length,
      ...entries.map((e) => {
        const val = regSheet.getRow(2).getCell(i + 1).value;
        return String(val ?? '').length;
      })
    );
    col.width = Math.min(Math.max(maxLen + 2, 12), 28);
  });

  // ── Sheet 3: Reimbursement Detail ─────────────────────────────────────────
  const reimbSheet = workbook.addWorksheet('Reimbursement Detail', {
    pageSetup: { orientation: 'portrait', fitToPage: true },
  });

  const reimbHeader = ['Emp ID', 'Employee Name', 'Category', 'Amount (₹)', 'Description', 'Submitted On'];
  const rHRow = reimbSheet.addRow(reimbHeader);
  rHRow.height = 36;
  rHRow.eachCell((cell) => { cell.style = headerStyle(); });

  if (reimbDetails.length === 0) {
    const noDataRow = reimbSheet.addRow(['No reimbursements included in this payroll run.', '', '', '', '', '']);
    reimbSheet.mergeCells(`A${noDataRow.number}:F${noDataRow.number}`);
    noDataRow.getCell(1).style = {
      font:      { italic: true, color: { argb: 'FF888888' } },
      alignment: { horizontal: 'center' },
    };
  } else {
    reimbDetails.forEach((rd, idx) => {
      const shade = idx % 2 === 1;
      const r = reimbSheet.addRow([
        rd.employeeId, rd.employeeName, rd.category,
        rd.amount, rd.description, rd.submittedOn,
      ]);
      r.height = 20;
      r.eachCell((cell, ci) => {
        cell.style = {
          ...dataStyle(shade),
          numFmt: ci === 4 ? '#,##0.00' : undefined,
          alignment: { horizontal: ci === 4 ? 'center' : 'left', vertical: 'middle' },
        };
      });
    });
  }

  reimbSheet.columns.forEach((col, i) => {
    const widths = [12, 22, 16, 14, 36, 16];
    col.width = widths[i] ?? 14;
  });

  return workbook.xlsx.writeBuffer();
}
